version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
